apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-bis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: root-bis
  project: default
  source:
    path: apps/
    repoURL: https://github.com/hellebore74/helm-chart2.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
